name: Deploy
on: [push, workflow_dispatch]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Install mdbook
              run: |
                  mkdir mdbook
                  curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
                  echo `pwd`/mdbook >> $GITHUB_PATH
            - name: Build docs site
              run: mdbook build
            - name: Deploy GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: book
